 INSERT INTO EXPERTISE_QUESTION(ID,LABEL,PRIORITY) VALUES(1, 'Multimedyada problem var mı?', 1);
 INSERT INTO EXPERTISE_QUESTION(ID,LABEL,PRIORITY) VALUES(2, 'Ruhsatta eksiklik var mı?', 2);
 INSERT INTO EXPERTISE_QUESTION(ID,LABEL,PRIORITY) VALUES(3, 'Aküde eksiklik/problem var mı?', 3);